### ISSUE TITLE
Support @Id annotation in addition to Persistable

### ISSUE THREAD

**Issue by sdeleuze** [jirutka/spring-data-jdbc-repository#1]
As shown in this [draft commit](https://github.com/sdeleuze/spring-data-jdbc-repository/commit/0b1a5095536cab9666f92e92d9192220c876d239), I think it could be interesting to support domain object that are not implementing `Persistable`. It would be less intrusive and consistent with what is done in Spring Data MongoDB for example.

@jirutka As described in [this comment](https://github.com/nurkiewicz/spring-data-jdbc-repository/issues/28#issuecomment-194582363) you seem to have some plan for a better support for the `isNew` logic. Any chance you can progress on that and on my side based on these improvements I could work on a PR for `@Id` support ?

**Comment by jirutka** [comment]
I'll implement support for `@Id` myself, in more modular fashion. I hope that I'll finish it during weekend and release a snapshot version for testing at least.

**Comment by sdeleuze** [comment]
Awesome, I will switch to `spring-data-jdbc-repository` and will send you my feedback. FYI I plan to use it in a talk I will give in several conferences about how to develop Spring Boot application with Kotlin using a lightweight stack (without JPA).

**Comment by jirutka** [comment]
Done, you can try 0.6.0-SNAPSHOT, it’s published in [JFrog Maven repository](https://github.com/jirutka/spring-data-jdbc-repository#how-to-get-it).

> I plan to use it in a talk I will give in several conferences about how to develop Spring Boot application with Kotlin using a lightweight stack (without JPA).

That’s great, I’m really glad for that! :smile_cat: Please let me know when a video record or slides will be available.

**Comment by jirutka** [comment]
BTW You may be also interested how I’m using spring-data-jdbc-repository in Groovy: [example](https://github.com/cvut/zuul-oaas/blob/master/zuul-oaas-persistence-jdbc/src/main/groovy/cz/cvut/zuul/oaas/persistence/JdbcAccessTokensRepo.groovy) (it’s quite hacked now, just for an idea).

**Comment by sdeleuze** [comment]
Awesome thanks! Here is my draft Kotlin app: https://github.com/sdeleuze/geospatial-messenger

Could you please fix https://github.com/jirutka/spring-data-jdbc-repository/issues/2 in order to allow me to switch on your 0.6.0-SNAPSHOT version (I am currently using my own fork)?

**Comment by DanielFran** [comment]
Awesome job! I have been using version 0.6.0-SNAPSHOT for some weeks now and seems working great!
Can you please confirm when you will release final version 0.6.0?
Many Thanks
