### ISSUE TITLE
Make it easier to custom method in JdbcRepository

### ISSUE THREAD

**Issue by sdeleuze** [jirutka/spring-data-jdbc-repository#2]
Currently `JdbcRepository` fields are `private` and there is not getter available. Implementing custom methods in classes extending `JdbcRepository` seems a valid use case to me, so maybe `JdbcRepository` fields should be `protected` instead of `private`. Any thoughts?

**Comment by jirutka** [comment]
What fields you'd like to read from subclasses?

**Comment by sdeleuze** [comment]
The one needed to implement custom methods seems to be `table`, `rowMapper`, `rowUnmapper`, `sqlGenerator` and `jdbcOperations`.

**Comment by virgiliu-ratoi-ec-ext** [comment]
Are there any plans to release this feature in the upcoming future?
